### ISSUE TITLE
hipscat margin cache api updates

### ISSUE THREAD

**Issue by maxwest-uw** [astronomy-commons/hipscat-import#103]
due to some of the changes in the hipscat package for the [new margin cache code](https://github.com/astronomy-commons/hipscat/pull/114), the API has been changed and might break the CI once hipscat has been updated. to ensure a smooth transition, i propose we do the following:
- [x] merge the new margin cache code into `hipscat`
- [x] pin `hipscat-import`'s dependency on `hipscat` to version `0.1.0`
- [x] release `hipscat==0.1.1`
- [x] merge in the `hipscat-import` compatibility changes + remove the pin on the `hipscat` dependency
- [x] release `hipscat-import==0.1.1`

(the last step might not be dependent on the margin cache changes, but can also be done whenever :])

**Comment by delucchi-cmu** [comment]
Will we need to pin hipscat-import's version of hipscat to >=0.1.1 after this?

**Comment by maxwest-uw** [comment]
good call, that's probably a good idea.
