### ISSUE TITLE
Add additional association table metadata to soap

### ISSUE THREAD

**Issue by smcguire-cmu** [astronomy-commons/hipscat-import#191]
In recent hipscat PRs [180](https://github.com/astronomy-commons/hipscat/pull/180) and [183](https://github.com/astronomy-commons/hipscat/pull/183), more metadata fields have been added to the association catalog info, which should be updated with SOAP.

**Comment by delucchi-cmu** [comment]
Has this been fixed by https://github.com/astronomy-commons/hipscat-import/pull/213
