### ISSUE TITLE
Make hipscat-import conda installable

### ISSUE THREAD

**Issue by nevencaplar** [astronomy-commons/hipscat-import#196]
See https://github.com/conda-forge/staged-recipes/pull/24833 for hipscat-import and associated packaged being made conda-installable. This ticket is to capture this work and progress from hipscat-import side.

**Comment by delucchi-cmu** [comment]
As of v0.2.1, the released tarball contains the .git_archival.txt file

https://github.com/astronomy-commons/hipscat-import/releases/tag/v0.2.1

**Comment by mjuric** [comment]
Done!

https://anaconda.org/conda-forge/hipscat-import
