### ISSUE TITLE
Reimport GAIA, epyc and PSC

### ISSUE THREAD

**Issue by nevencaplar** [astronomy-commons/hipscat-import#221]
GAIA catalog that we use on University of Washington cluster (epyc) and Carnegie Mellon (PSC) has been imported with LSD2. This seems to have a bug in _hipscat_index creation. Reimport using hipscat-import on both machines.

**Comment by delucchi-cmu** [comment]
The gaia dr3 object catalog has been re-imported at /data3/epyc/data3/hipscat/catalogs/gaia_dr3/gaia

- [ ] recreate 10arcsec margin
- [ ] recreate index over source_id (was over designation, but i think source_id will be more useful)
- [ ] add almanac entries for all of these

**Comment by delucchi-cmu** [comment]
gaia has been re-imported in /data3/epyc/data3/hipscat/catalogs/gaia_dr3/:
- gaia/ - object catalog
- gaia_source_id_index/ - index catalog over source_id
- gaia_10arcs/ - margin cache using 10 arcseconds

almanac entries have been created for all these new catalogs.

**Comment by hombit** [comment]
Transfered to PSC's bridges2: `/ocean/projects/phy210048p/shared/hipscat/catalogs/gaia_dr3`
