### ISSUE TITLE
Format - file extension ambiguity

### ISSUE THREAD

**Issue by hombit** [astronomy-commons/hipscat-import#229]
`input_format` argument solves two different problems right now: it is used to find files in a folder by extension and it is used to select a file reader class. However, this approach has some limitations, since extensions do not necessary correspond to format exactly:
1. Extension can be a bit different for the same format, for example for FITS files it can be `.fits`, `.FITS` or `.FIT`;
2. compressed files would have double extensions, and while we handle it for CSV files, it is also common for FITS files to be gziped, see [Elasticc](https://portal.nersc.gov/cfs/lsst/DESC_TD_PUBLIC/ELASTICC/ELASTICC2_TRAINING_SAMPLE_2/ELASTICC2_TRAIN_02_CART/) for an example;
3. some extensions could correspond to multiple formats, for example Gaia ESCV files have `.csv.gz` extensions, see #225.

**Comment by nevencaplar** [comment]
@hombit Can you describe a bit better what problems this is causing and what the proposed actions are you suggesting? For instance when extension is  .fits, .FITS or .FIT - what are the consequences of that?

**Comment by hombit** [comment]
Currently, it is a bit confusing that `input_format` argument sets both file format and file extension. If you have a catalog represented with `.fits` you do
```python
ImportArguments(
    input_format="fits",
    input_path="./data/",
    ...
)
```
This will use `./data/*.fits` files

But you have `.FIT.GZ` files, you should do
```python
ImportArguments(
    # We cannot use FIT, fits.gz, fits.fz, etc here
    input_format="fits",
    input_file_list=glob('./data/*.FIT.GZ'),
    ...
)
```

I find it confusing, because  in my mind format != extension, and I do not expect this different behavior for different file extensions representing the same file format.

Also, see, above, it would also cause some ambiguity when we implement more data formats, such as ESCV, VOTable, etc.
