### ISSUE TITLE
Reimport ZTF with larger ~100 mb parquet file sizes.

### ISSUE THREAD

**Issue by nevencaplar** [astronomy-commons/hipscat-import#237]
Reimport ZTF with larger ~100 mb parquet file sizes (on epyc, PSC). This is to reduce the number of partitions.

**Comment by delucchi-cmu** [comment]
Note `ztf_zource` instead of `ztf_source`. 

```
catalog_dir = "/data3/epyc/data3/hipscat/catalogs/ztf_axs/ztf_zource/"

healpix orders: [2 3 4 5 6 7 8 9]
num partitions: 41679
------
min size_on_disk: 0.00
max size_on_disk: 0.46
total size_on_disk: 8343.36

small-ish 	: 2779 	(6.7 %)
sweet-spot 	: 38900 	(93.3 %)
```
and a histogram of leaf parquet file sizes (units are GB)
![image](https://github.com/astronomy-commons/hipscat-import/assets/113376043/d277fe3d-2c8a-4452-8fed-86d276b2a00b)
