### ISSUE TITLE
Traceback when importing fails

### ISSUE THREAD

**Issue by nevencaplar** [astronomy-commons/hipscat-import#273]
https://github.com/astronomy-commons/hipscat-import/blob/62a30a0768e5035c02df19d26037c369d007618f/src/hipscat_import/pipeline_resume_plan.py#L137

1. Include the traceback, instead of just a general error message 
2. In the exception below, we refer a user to logs. Be more specific, i.e., how to get logs or where they are placed.

**Comment by delucchi-cmu** [comment]
I think this has been addressed by https://github.com/astronomy-commons/hipscat-import/pull/290

**Comment by nevencaplar** [comment]
Do we actually generate logs when importing catalogs?
