### ISSUE TITLE
Progress bars are missing in my Jupyter environment (PSC)

### ISSUE THREAD

**Issue by hombit** [astronomy-commons/hipscat-import#327]
**Bug report**

When I use the latest release on the PSC ondemand service, I don't see progress bars in a Jupyter Lab notebook:

<img width="838" alt="image" src="https://github.com/astronomy-commons/hipscat-import/assets/1784493/8fdc2502-2e7f-4b39-b094-f2271b709e74">

I use Python 3.12 with the conda environment

**Before submitting**
Please check the following:

- [x] I have described the situation in which the bug arose, including what code was executed, information about my environment, and any applicable data others will need to reproduce the problem.
- [x] I have included available evidence of the unexpected behavior (including error messages, screenshots, and/or plots) as well as a descriprion of what I expected instead.
- [ ] If I have a solution in mind, I have provided an explanation and/or pseudocode and/or task list.

**Comment by hombit** [comment]
I was about to say that we may recommend to install `ipywidgets` in this error message, but its installation completely broke my PSC Jupyter Lab

**Comment by hombit** [comment]
My Jupyter is fixed now, but `ipywidgets` didn't really help. Could we have an option to use a "simple" tqdm progress bar? Because a naive code like this works for me:

```python
from tqdm import tqdm

for _ in tqdm(range(100)):
    pass
```

while `from tqdm.auto import tqdm` does not.

**Comment by delucchi-cmu** [comment]
To clarify, are you suggesting/approve of potentially having two flag on the arguments?

`progress_bar (bool)`: should we display any progress bar at all
`simple_progress_bar (bool)`: if we're displaying a progress bar, make it a simple (plain text, non-widgety one).

I also want to cross-reference this issue that motivated using the widget-style progress bar in the first place: https://github.com/astronomy-commons/lsdb/issues/167

**Comment by hombit** [comment]
> progress_bar (bool): should we display any progress bar at all
simple_progress_bar (bool): if we're displaying a progress bar, make it a simple (plain text, non-widgety one).

Is there any way to check if widgets are active and do this choice for user?

> I also want to cross-reference this issue that motivated using the widget-style progress bar in the first place: https://github.com/astronomy-commons/lsdb/issues/167

The new progress bar is pretty, I think it was a good change!
