### ISSUE TITLE
Validate imported data for scientific use

### ISSUE THREAD

**Issue by delucchi-cmu** [astronomy-commons/hipscat-import#93]
MAST folks are interested in strategies for making sure that we retain rounding/precision in our import process, particularly for floating point values.

One potential issue is that we're reading their data that has been exported from a SQL database (where they're presumably happy with the level of control on their rounding/precision) into a CSV, and converting this string representation again into a float can be lossy.

The catalog providers may have some format or units they can provide to help us in this, but they will vary by catalog.  e.g. for Allwise, we see descriptions like `ra	%11.7f	deg` ([link](https://wise2.ipac.caltech.edu/docs/release/allwise/expsup/sec2_1a.html))

**Comment by nevencaplar** [comment]
Same as https://github.com/astronomy-commons/hipscat-import/issues/118
